package org.siemac.metamac.internal.web.concept.model.ds;

public enum ConceptSchemeProcStatusEnum {
    DRAFT, VALIDATION_REJECTED, PENDING_PUBLICATION, INTERNAL_PUBLICATION_FAILED, INTERNALLY_PUBLISHED, EXTERNAL_PUBLICATION_FAILED, EXTERNALLY_PUBLISHED;
}
