-- ###########################################
-- # Create
-- ###########################################

-- Create normal entities
    
CREATE TABLE TB_M_CATEGORIES (
  TB_CATEGORIES BIGINT NOT NULL

);


CREATE TABLE TB_M_CAT_SCHEMES_VERSIONS (
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR(50),
  PRODUCTION_VALIDATION_DATE DATETIME,
  PRODUCTION_VALIDATION_USER VARCHAR(255),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR(50),
  DIFFUSION_VALIDATION_DATE DATETIME,
  DIFFUSION_VALIDATION_USER VARCHAR(255),
  INTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  INTERNAL_PUBLICATION_DATE DATETIME,
  INTERNAL_PUBLICATION_USER VARCHAR(255),
  EXTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  EXTERNAL_PUBLICATION_DATE DATETIME,
  EXTERNAL_PUBLICATION_USER VARCHAR(255),
  IS_EXT_PUBLICATION_FAILED BIT,
  EXT_PUBLICATION_FAILED_DATE_TZ VARCHAR(50),
  EXT_PUBLICATION_FAILED_DATE DATETIME,
  PROC_STATUS VARCHAR(255) NOT NULL,
  TB_CAT_SCHEMES_VERSIONS BIGINT NOT NULL

);


CREATE TABLE TB_M_VARIABLES (
  ID BIGINT NOT NULL,
  VALID_FROM_TZ VARCHAR(50),
  VALID_FROM DATETIME,
  VALID_TO_TZ VARCHAR(50),
  VALID_TO DATETIME,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  NAMEABLE_ARTEFACT_FK BIGINT NOT NULL,
  SHORT_NAME_FK BIGINT NOT NULL,
  REPLACED_BY_VARIABLE_FK BIGINT
);


CREATE TABLE TB_M_VARIABLE_ELEMENTS (
  ID BIGINT NOT NULL,
  VALID_FROM_TZ VARCHAR(50),
  VALID_FROM DATETIME,
  VALID_TO_TZ VARCHAR(50),
  VALID_TO DATETIME,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  NAMEABLE_ARTEFACT_FK BIGINT NOT NULL,
  SHORT_NAME_FK BIGINT NOT NULL,
  VARIABLE_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_CODES (
  VARIABLE_ELEMENT_FK BIGINT,
  SHORT_NAME_FK BIGINT,
  TB_CODES BIGINT NOT NULL

);


CREATE TABLE TB_M_CODELIST_FAMILIES (
  ID BIGINT NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  NAMEABLE_ARTEFACT_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_CODELISTS_VERSIONS (
  IS_RECOMMENDED BIT,
  SHORT_NAME_FK BIGINT,
  CODELIST_FAMILY_FK BIGINT,
  VARIABLE_FK BIGINT,
  REPLACED_BY_CODELIST_FK BIGINT,
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR(50),
  PRODUCTION_VALIDATION_DATE DATETIME,
  PRODUCTION_VALIDATION_USER VARCHAR(255),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR(50),
  DIFFUSION_VALIDATION_DATE DATETIME,
  DIFFUSION_VALIDATION_USER VARCHAR(255),
  INTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  INTERNAL_PUBLICATION_DATE DATETIME,
  INTERNAL_PUBLICATION_USER VARCHAR(255),
  EXTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  EXTERNAL_PUBLICATION_DATE DATETIME,
  EXTERNAL_PUBLICATION_USER VARCHAR(255),
  IS_EXT_PUBLICATION_FAILED BIT,
  EXT_PUBLICATION_FAILED_DATE_TZ VARCHAR(50),
  EXT_PUBLICATION_FAILED_DATE DATETIME,
  PROC_STATUS VARCHAR(255) NOT NULL,
  ACCESS_TYPE VARCHAR(255),
  TB_CODELISTS_VERSIONS BIGINT NOT NULL

);


CREATE TABLE TB_M_CODELIST_ORDER_VISUAL (
  ID BIGINT NOT NULL,
  IDENTIFIER VARCHAR(255) NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  NAME_FK BIGINT,
  CODELIST_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_CODE_ORDER_VISUAL (
  ID BIGINT NOT NULL,
  CODE_INDEX BIGINT NOT NULL,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  CODE_FK BIGINT NOT NULL,
  CODELIST_VISUALISATION_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_VARIABLE_FAMILIES (
  ID BIGINT NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  NAMEABLE_ARTEFACT_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_LIS_CONCEPT_TYPES (
  ID BIGINT NOT NULL,
  IDENTIFIER VARCHAR(255) NOT NULL,
  DESCRIPTION_FK BIGINT
);


CREATE TABLE TB_M_CONCEPTS (
  PLURAL_NAME_FK BIGINT,
  ACRONYM_FK BIGINT,
  DESCRIPTION_SOURCE_FK BIGINT,
  CONTEXT_FK BIGINT,
  DOC_METHOD_FK BIGINT,
  CONCEPT_TYPE_FK BIGINT,
  DERIVATION_FK BIGINT,
  LEGAL_ACTS_FK BIGINT,
  EXTENDS_FK BIGINT,
  VARIABLE_FK BIGINT,
  SDMX_RELATED_ARTEFACT VARCHAR(255),
  TB_CONCEPTS BIGINT NOT NULL

);


CREATE TABLE TB_M_CONCEPT_SCHEMES_VERSIONS (
  RELATED_OPERATION_FK BIGINT,
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR(50),
  PRODUCTION_VALIDATION_DATE DATETIME,
  PRODUCTION_VALIDATION_USER VARCHAR(255),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR(50),
  DIFFUSION_VALIDATION_DATE DATETIME,
  DIFFUSION_VALIDATION_USER VARCHAR(255),
  INTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  INTERNAL_PUBLICATION_DATE DATETIME,
  INTERNAL_PUBLICATION_USER VARCHAR(255),
  EXTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  EXTERNAL_PUBLICATION_DATE DATETIME,
  EXTERNAL_PUBLICATION_USER VARCHAR(255),
  IS_EXT_PUBLICATION_FAILED BIT,
  EXT_PUBLICATION_FAILED_DATE_TZ VARCHAR(50),
  EXT_PUBLICATION_FAILED_DATE DATETIME,
  PROC_STATUS VARCHAR(255) NOT NULL,
  CONCEPT_SCHEME_TYPE VARCHAR(255) NOT NULL,
  TB_CONCEPT_SCHEMES_VERSIONS BIGINT NOT NULL

);


CREATE TABLE TB_M_DATASTRUCTURE_VERSIONS (
  AUTO_OPEN BIT,
  SHOW_DECIMALS INT,
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR(50),
  PRODUCTION_VALIDATION_DATE DATETIME,
  PRODUCTION_VALIDATION_USER VARCHAR(255),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR(50),
  DIFFUSION_VALIDATION_DATE DATETIME,
  DIFFUSION_VALIDATION_USER VARCHAR(255),
  INTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  INTERNAL_PUBLICATION_DATE DATETIME,
  INTERNAL_PUBLICATION_USER VARCHAR(255),
  EXTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  EXTERNAL_PUBLICATION_DATE DATETIME,
  EXTERNAL_PUBLICATION_USER VARCHAR(255),
  IS_EXT_PUBLICATION_FAILED BIT,
  EXT_PUBLICATION_FAILED_DATE_TZ VARCHAR(50),
  EXT_PUBLICATION_FAILED_DATE DATETIME,
  PROC_STATUS VARCHAR(255) NOT NULL,
  TB_DATASTRUCTURE_VERSIONS BIGINT NOT NULL

);


CREATE TABLE TB_M_DIMENSION_ORDERS (
  ID BIGINT NOT NULL,
  DIM_ORDER INT NOT NULL,
  UUID VARCHAR(36) NOT NULL,
  VERSION BIGINT NOT NULL,
  DIM_COMPONENT_FK BIGINT NOT NULL,
  DSD_VERSION_HEADING_FK BIGINT,
  DSD_VERSION_STUB_FK BIGINT
);


CREATE TABLE TB_M_MEASURE_DIM_PRECISIONS (
  ID BIGINT NOT NULL,
  SHOW_DECIMAL_PRECISION INT NOT NULL,
  UUID VARCHAR(36) NOT NULL,
  VERSION BIGINT NOT NULL,
  M_CODE_FK BIGINT NOT NULL,
  DSD_VERSION_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_ORGANISATIONS (
  TB_ORGANISATIONS BIGINT NOT NULL

);


CREATE TABLE TB_M_ORG_SCHEMES_VERSIONS (
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR(50),
  PRODUCTION_VALIDATION_DATE DATETIME,
  PRODUCTION_VALIDATION_USER VARCHAR(255),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR(50),
  DIFFUSION_VALIDATION_DATE DATETIME,
  DIFFUSION_VALIDATION_USER VARCHAR(255),
  INTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  INTERNAL_PUBLICATION_DATE DATETIME,
  INTERNAL_PUBLICATION_USER VARCHAR(255),
  EXTERNAL_PUBLICATION_DATE_TZ VARCHAR(50),
  EXTERNAL_PUBLICATION_DATE DATETIME,
  EXTERNAL_PUBLICATION_USER VARCHAR(255),
  IS_EXT_PUBLICATION_FAILED BIT,
  EXT_PUBLICATION_FAILED_DATE_TZ VARCHAR(50),
  EXT_PUBLICATION_FAILED_DATE DATETIME,
  PROC_STATUS VARCHAR(255) NOT NULL,
  TB_ORG_SCHEMES_VERSIONS BIGINT NOT NULL

);



-- Create many to many relations
    
CREATE TABLE TB_M_CONCEPT_RELATED (
  CONCEPT_RELATED_FK BIGINT NOT NULL,
  CONCEPT_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_CONCEPT_ROLES (
  CONCEPT_ROLE_FK BIGINT NOT NULL,
  CONCEPT_FK BIGINT NOT NULL
);


CREATE TABLE TB_M_VAR_FAMILIES_VARIABLES (
  VARIABLE_FAMILY_FK BIGINT NOT NULL,
  VARIABLE_FK BIGINT NOT NULL
);



-- Primary keys
    
ALTER TABLE TB_M_VARIABLES ADD CONSTRAINT PK_TB_M_VARIABLES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_VARIABLE_ELEMENTS ADD CONSTRAINT PK_TB_M_VARIABLE_ELEMENTS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_CODELIST_FAMILIES ADD CONSTRAINT PK_TB_M_CODELIST_FAMILIES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_CODELIST_ORDER_VISUAL ADD CONSTRAINT PK_TB_M_CODELIST_ORDER_VISUAL
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_CODE_ORDER_VISUAL ADD CONSTRAINT PK_TB_M_CODE_ORDER_VISUAL
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_VARIABLE_FAMILIES ADD CONSTRAINT PK_TB_M_VARIABLE_FAMILIES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_LIS_CONCEPT_TYPES ADD CONSTRAINT PK_TB_M_LIS_CONCEPT_TYPES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_DIMENSION_ORDERS ADD CONSTRAINT PK_TB_M_DIMENSION_ORDERS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_M_MEASURE_DIM_PRECISIONS ADD CONSTRAINT PK_TB_M_MEASURE_DIM_PRECISIONS
	PRIMARY KEY (ID)
;

    
ALTER TABLE TB_M_CONCEPT_RELATED ADD CONSTRAINT PK_TB_M_CONCEPT_RELATED
	PRIMARY KEY (CONCEPT_RELATED_FK, CONCEPT_FK)
;

ALTER TABLE TB_M_CONCEPT_ROLES ADD CONSTRAINT PK_TB_M_CONCEPT_ROLES
	PRIMARY KEY (CONCEPT_ROLE_FK, CONCEPT_FK)
;

ALTER TABLE TB_M_VAR_FAMILIES_VARIABLES ADD CONSTRAINT PK_TB_M_VAR_FAMILIES_VARIABLES
	PRIMARY KEY (VARIABLE_FAMILY_FK, VARIABLE_FK)
;


-- Unique constraints



ALTER TABLE TB_M_VARIABLES
    ADD CONSTRAINT UQ_TB_M_VARIABLES UNIQUE (UUID)
;


ALTER TABLE TB_M_VARIABLE_ELEMENTS
    ADD CONSTRAINT UQ_TB_M_VARIABLE_ELEMENTS UNIQUE (UUID)
;



ALTER TABLE TB_M_CODELIST_FAMILIES
    ADD CONSTRAINT UQ_TB_M_CODELIST_FAMILIES UNIQUE (UUID)
;



ALTER TABLE TB_M_CODELIST_ORDER_VISUAL
    ADD CONSTRAINT UQ_TB_M_CODELIST_ORDER_VISUAL UNIQUE (UUID)
;


ALTER TABLE TB_M_CODE_ORDER_VISUAL
    ADD CONSTRAINT UQ_TB_M_CODE_ORDER_VISUAL UNIQUE (UUID)
;


ALTER TABLE TB_M_VARIABLE_FAMILIES
    ADD CONSTRAINT UQ_TB_M_VARIABLE_FAMILIES UNIQUE (UUID)
;


ALTER TABLE TB_M_LIS_CONCEPT_TYPES
	ADD CONSTRAINT UQ_TB_M_LIS_CONCEPT_TYPES UNIQUE (ID)
;





ALTER TABLE TB_M_DIMENSION_ORDERS
    ADD CONSTRAINT UQ_TB_M_DIMENSION_ORDERS UNIQUE (UUID)
;


ALTER TABLE TB_M_MEASURE_DIM_PRECISIONS
    ADD CONSTRAINT UQ_TB_M_MEASURE_DIM_PRECISIONS UNIQUE (UUID)
;





-- Foreign key constraints
ALTER TABLE TB_M_CATEGORIES ADD CONSTRAINT FK_TB_M_CATEGORIES_TB_CATEGORIES
	FOREIGN KEY (TB_CATEGORIES) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_CAT_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_M_CAT_SCHEMES_VERSIONS_TB_CAT_SCHEMES_VERSIONS
	FOREIGN KEY (TB_CAT_SCHEMES_VERSIONS) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;
ALTER TABLE TB_M_CODES ADD CONSTRAINT FK_TB_M_CODES_TB_CODES
	FOREIGN KEY (TB_CODES) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_CODELISTS_VERSIONS ADD CONSTRAINT FK_TB_M_CODELISTS_VERSIONS_TB_CODELISTS_VERSIONS
	FOREIGN KEY (TB_CODELISTS_VERSIONS) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_TB_CONCEPTS
	FOREIGN KEY (TB_CONCEPTS) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_CONCEPT_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_M_CONCEPT_SCHEMES_VERSIONS_TB_CONCEPT_SCHEMES_VERSIONS
	FOREIGN KEY (TB_CONCEPT_SCHEMES_VERSIONS) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;
ALTER TABLE TB_M_DATASTRUCTURE_VERSIONS ADD CONSTRAINT FK_TB_M_DATASTRUCTURE_VERSIONS_TB_DATASTRUCTURE_VERSIONS
	FOREIGN KEY (TB_DATASTRUCTURE_VERSIONS) REFERENCES TB_STRUCTURES_VERSIONS (ID)
;
ALTER TABLE TB_M_ORGANISATIONS ADD CONSTRAINT FK_TB_M_ORGANISATIONS_TB_ORGANISATIONS
	FOREIGN KEY (TB_ORGANISATIONS) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_ORG_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_M_ORG_SCHEMES_VERSIONS_TB_ORG_SCHEMES_VERSIONS
	FOREIGN KEY (TB_ORG_SCHEMES_VERSIONS) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;


  
  
  
  
ALTER TABLE TB_M_VARIABLES ADD CONSTRAINT FK_TB_M_VARIABLES_NAMEABLE_ARTEFACT_FK
	FOREIGN KEY (NAMEABLE_ARTEFACT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_M_VARIABLES ADD CONSTRAINT FK_TB_M_VARIABLES_SHORT_NAME_FK
	FOREIGN KEY (SHORT_NAME_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_VARIABLES ADD CONSTRAINT FK_TB_M_VARIABLES_REPLACED_BY_VARIABLE_FK
	FOREIGN KEY (REPLACED_BY_VARIABLE_FK) REFERENCES TB_M_VARIABLES (ID)
;

  
ALTER TABLE TB_M_VARIABLE_ELEMENTS ADD CONSTRAINT FK_TB_M_VARIABLE_ELEMENTS_NAMEABLE_ARTEFACT_FK
	FOREIGN KEY (NAMEABLE_ARTEFACT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_M_VARIABLE_ELEMENTS ADD CONSTRAINT FK_TB_M_VARIABLE_ELEMENTS_SHORT_NAME_FK
	FOREIGN KEY (SHORT_NAME_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_VARIABLE_ELEMENTS ADD CONSTRAINT FK_TB_M_VARIABLE_ELEMENTS_VARIABLE_FK
	FOREIGN KEY (VARIABLE_FK) REFERENCES TB_M_VARIABLES (ID)
;

  
ALTER TABLE TB_M_CODES ADD CONSTRAINT FK_TB_M_CODES_VARIABLE_ELEMENT_FK
	FOREIGN KEY (VARIABLE_ELEMENT_FK) REFERENCES TB_M_VARIABLE_ELEMENTS (ID)
;
ALTER TABLE TB_M_CODES ADD CONSTRAINT FK_TB_M_CODES_SHORT_NAME_FK
	FOREIGN KEY (SHORT_NAME_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_M_CODELIST_FAMILIES ADD CONSTRAINT FK_TB_M_CODELIST_FAMILIES_NAMEABLE_ARTEFACT_FK
	FOREIGN KEY (NAMEABLE_ARTEFACT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_M_CODELISTS_VERSIONS ADD CONSTRAINT FK_TB_M_CODELISTS_VERSIONS_SHORT_NAME_FK
	FOREIGN KEY (SHORT_NAME_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CODELISTS_VERSIONS ADD CONSTRAINT FK_TB_M_CODELISTS_VERSIONS_CODELIST_FAMILY_FK
	FOREIGN KEY (CODELIST_FAMILY_FK) REFERENCES TB_M_CODELIST_FAMILIES (ID)
;
ALTER TABLE TB_M_CODELISTS_VERSIONS ADD CONSTRAINT FK_TB_M_CODELISTS_VERSIONS_VARIABLE_FK
	FOREIGN KEY (VARIABLE_FK) REFERENCES TB_M_VARIABLES (ID)
;
ALTER TABLE TB_M_CODELISTS_VERSIONS ADD CONSTRAINT FK_TB_M_CODELISTS_VERSIONS_REPLACED_BY_CODELIST_FK
	FOREIGN KEY (REPLACED_BY_CODELIST_FK) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;

  
ALTER TABLE TB_M_CODELIST_ORDER_VISUAL ADD CONSTRAINT FK_TB_M_CODELIST_ORDER_VISUAL_NAME_FK
	FOREIGN KEY (NAME_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CODELIST_ORDER_VISUAL ADD CONSTRAINT FK_TB_M_CODELIST_ORDER_VISUAL_CODELIST_FK
	FOREIGN KEY (CODELIST_FK) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID) ON DELETE CASCADE
;

  
ALTER TABLE TB_M_CODE_ORDER_VISUAL ADD CONSTRAINT FK_TB_M_CODE_ORDER_VISUAL_CODE_FK
	FOREIGN KEY (CODE_FK) REFERENCES TB_ITEMS (ID) ON DELETE CASCADE
;
ALTER TABLE TB_M_CODE_ORDER_VISUAL ADD CONSTRAINT FK_TB_M_CODE_ORDER_VISUAL_CODELIST_VISUALISATION_FK
	FOREIGN KEY (CODELIST_VISUALISATION_FK) REFERENCES TB_M_CODELIST_ORDER_VISUAL (ID) ON DELETE CASCADE
;

  
ALTER TABLE TB_M_VARIABLE_FAMILIES ADD CONSTRAINT FK_TB_M_VARIABLE_FAMILIES_NAMEABLE_ARTEFACT_FK
	FOREIGN KEY (NAMEABLE_ARTEFACT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_M_LIS_CONCEPT_TYPES ADD CONSTRAINT FK_TB_M_LIS_CONCEPT_TYPES_DESCRIPTION_FK
	FOREIGN KEY (DESCRIPTION_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_PLURAL_NAME_FK
	FOREIGN KEY (PLURAL_NAME_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_ACRONYM_FK
	FOREIGN KEY (ACRONYM_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_DESCRIPTION_SOURCE_FK
	FOREIGN KEY (DESCRIPTION_SOURCE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_CONTEXT_FK
	FOREIGN KEY (CONTEXT_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_DOC_METHOD_FK
	FOREIGN KEY (DOC_METHOD_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_CONCEPT_TYPE_FK
	FOREIGN KEY (CONCEPT_TYPE_FK) REFERENCES TB_M_LIS_CONCEPT_TYPES (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_DERIVATION_FK
	FOREIGN KEY (DERIVATION_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_LEGAL_ACTS_FK
	FOREIGN KEY (LEGAL_ACTS_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_EXTENDS_FK
	FOREIGN KEY (EXTENDS_FK) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_CONCEPTS ADD CONSTRAINT FK_TB_M_CONCEPTS_VARIABLE_FK
	FOREIGN KEY (VARIABLE_FK) REFERENCES TB_M_VARIABLES (ID)
;

  
ALTER TABLE TB_M_CONCEPT_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_M_CONCEPT_SCHEMES_VERSIONS_RELATED_OPERATION_FK
	FOREIGN KEY (RELATED_OPERATION_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;

  
  
  
ALTER TABLE TB_M_DIMENSION_ORDERS ADD CONSTRAINT FK_TB_M_DIMENSION_ORDERS_DIM_COMPONENT_FK
	FOREIGN KEY (DIM_COMPONENT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_M_DIMENSION_ORDERS ADD CONSTRAINT FK_TB_M_DIMENSION_ORDERS_DSD_VERSION_HEADING_FK
	FOREIGN KEY (DSD_VERSION_HEADING_FK) REFERENCES TB_STRUCTURES_VERSIONS (ID) ON DELETE CASCADE
;
ALTER TABLE TB_M_DIMENSION_ORDERS ADD CONSTRAINT FK_TB_M_DIMENSION_ORDERS_DSD_VERSION_STUB_FK
	FOREIGN KEY (DSD_VERSION_STUB_FK) REFERENCES TB_STRUCTURES_VERSIONS (ID) ON DELETE CASCADE
;

  
ALTER TABLE TB_M_MEASURE_DIM_PRECISIONS ADD CONSTRAINT FK_TB_M_MEASURE_DIM_PRECISIONS_M_CODE_FK
	FOREIGN KEY (M_CODE_FK) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_MEASURE_DIM_PRECISIONS ADD CONSTRAINT FK_TB_M_MEASURE_DIM_PRECISIONS_DSD_VERSION_FK
	FOREIGN KEY (DSD_VERSION_FK) REFERENCES TB_STRUCTURES_VERSIONS (ID) ON DELETE CASCADE
;

  
  
  
  
  

ALTER TABLE TB_M_CONCEPT_RELATED ADD CONSTRAINT FK_TB_M_CONCEPT_RELATED_CONCEPT_RELATED_FK
	FOREIGN KEY (CONCEPT_RELATED_FK) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_CONCEPT_RELATED ADD CONSTRAINT FK_TB_M_CONCEPT_RELATED_CONCEPT_FK
	FOREIGN KEY (CONCEPT_FK) REFERENCES TB_ITEMS (ID)
;

  
ALTER TABLE TB_M_CONCEPT_ROLES ADD CONSTRAINT FK_TB_M_CONCEPT_ROLES_CONCEPT_ROLE_FK
	FOREIGN KEY (CONCEPT_ROLE_FK) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_M_CONCEPT_ROLES ADD CONSTRAINT FK_TB_M_CONCEPT_ROLES_CONCEPT_FK
	FOREIGN KEY (CONCEPT_FK) REFERENCES TB_ITEMS (ID)
;

  
ALTER TABLE TB_M_VAR_FAMILIES_VARIABLES ADD CONSTRAINT FK_TB_M_VAR_FAMILIES_VARIABLES_VARIABLE_FAMILY_FK
	FOREIGN KEY (VARIABLE_FAMILY_FK) REFERENCES TB_M_VARIABLE_FAMILIES (ID)
;
ALTER TABLE TB_M_VAR_FAMILIES_VARIABLES ADD CONSTRAINT FK_TB_M_VAR_FAMILIES_VARIABLES_VARIABLE_FK
	FOREIGN KEY (VARIABLE_FK) REFERENCES TB_M_VARIABLES (ID)
;

  



