-- AGENCY SCHEME: SDMX

INSERT INTO TB_M_ORG_SCHEMES_VERSIONS
	(TB_ORG_SCHEMES_VERSIONS, PROC_STATUS, 
     PRODUCTION_VALIDATION_DATE_TZ, PRODUCTION_VALIDATION_DATE, PRODUCTION_VALIDATION_USER,
     DIFFUSION_VALIDATION_DATE_TZ, DIFFUSION_VALIDATION_DATE, DIFFUSION_VALIDATION_USER,
     INTERNAL_PUBLICATION_DATE_TZ, INTERNAL_PUBLICATION_DATE, INTERNAL_PUBLICATION_USER,
     EXTERNAL_PUBLICATION_DATE_TZ, EXTERNAL_PUBLICATION_DATE, EXTERNAL_PUBLICATION_USER)
VALUES
	(IDENT_CURRENT('TB_ITEM_SCHEMES_VERSIONS'), 'INTERNALLY_PUBLISHED', 
	'Europe/London', convert(datetime, '2012-01-01 12:00:00', 120), 'Metamac',
	'Europe/London', convert(datetime, '2012-01-01 12:00:00', 120), 'Metamac',
	'Europe/London', convert(datetime, '2012-01-01 12:00:00', 120), 'Metamac',
	null, null, null
	);

