-- AGENCY SCHEME: SDMX

INSERT INTO TB_M_ORG_SCHEMES_VERSIONS
	(TB_ORG_SCHEMES_VERSIONS, PROC_STATUS)
VALUES
	(FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('ITEM_SCHEMES_VERSIONS') - 1, 'DRAFT');

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'M_ORG_SCHEMES_VERSIONS';