-- AGENCY
INSERT INTO TB_M_ORGANISATIONS (TB_ORGANISATIONS) VALUES (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('ITEMS') - 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'M_ORGANISATIONS';
