-- AGENCY
INSERT INTO TB_M_ORGANISATIONS (TB_ORGANISATIONS) VALUES (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('ORGANISATIONS') - 2);
INSERT INTO TB_M_ORGANISATIONS (TB_ORGANISATIONS) VALUES (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('ORGANISATIONS') - 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 2 WHERE SEQUENCE_NAME = 'M_ORGANISATIONS';

commit;