
    
-- ###########################################
-- # Drop
-- ###########################################
-- Drop index
  
  
  
  
  


-- Drop many to many relations
    
DROP TABLE TB_M_VAR_FAMILIES_VARIABLES CASCADE;

DROP TABLE TB_M_VAR_ELEM_OP_TARGETS CASCADE;

DROP TABLE TB_M_VAR_ELEM_OP_SOURCES CASCADE;

DROP TABLE TB_M_CONCEPT_ROLES CASCADE;

DROP TABLE TB_M_CONCEPT_RELATED CASCADE;

-- Drop normal entities
    
DROP TABLE TB_M_ORG_SCHEMES_VERSIONS CASCADE;

DROP TABLE TB_M_ORGANISATIONS CASCADE;

DROP TABLE TB_M_MEASURE_DIM_PRECISIONS CASCADE;

DROP TABLE TB_M_DIM_VIS_INFO CASCADE;

DROP TABLE TB_M_DIMENSION_ORDERS CASCADE;

DROP TABLE TB_M_DATASTRUCTURE_VERSIONS CASCADE;

DROP TABLE TB_M_CONCEPT_SCHEMES_VERSIONS CASCADE;

DROP TABLE TB_M_CONCEPTS CASCADE;

DROP TABLE TB_M_QUANTITIES CASCADE;

DROP TABLE TB_M_LIS_CONCEPT_TYPES CASCADE;

DROP TABLE TB_M_VARIABLE_FAMILIES CASCADE;

DROP TABLE TB_M_VAR_ELEM_OPERATIONS CASCADE;

DROP TABLE TB_M_CODELIST_OPENNESS_VIS CASCADE;

DROP TABLE TB_M_CODELISTS_VERSIONS CASCADE;

DROP TABLE TB_M_CODELIST_ORDER_VIS CASCADE;

DROP TABLE TB_M_CODELIST_FAMILIES CASCADE;

DROP TABLE TB_M_CODES CASCADE;

DROP TABLE TB_M_VARIABLE_ELEMENTS CASCADE;

DROP TABLE TB_M_VARIABLES CASCADE;

DROP TABLE TB_M_CAT_SCHEMES_VERSIONS CASCADE;

DROP TABLE TB_M_CATEGORIES CASCADE;

DROP TABLE TB_MISC_VALUES CASCADE;


-- Drop pk sequence

DROP TABLE TB_ENTITIES_TO_DELETE;