package org.siemac.metamac.srm.web.shared;

import java.io.Serializable;

public enum StructuralResourcesRelationEnum implements Serializable {

    CONCEPT_SCHEMES_WITH_DSD_PRIMARY_MEASURE,
    CONCEPT_WITH_DSD_PRIMARY_MEASURE,
    CODELIST_WITH_DSD_PRIMARY_MEASURE_ENUMERATED_REPRESENTATION,
    CONCEPT_SCHEMES_WITH_DSD_DIMENSION,
    CONCEPT_WITH_DSD_DIMENSION,
    CONCEPT_SCHEMES_WITH_DSD_TIME_DIMENSION,
    CONCEPT_WITH_DSD_TIME_DIMENSION,
    CONCEPT_SCHEMES_WITH_DSD_MEASURE_DIMENSION,
    CONCEPT_WITH_DSD_MEASURE_DIMENSION,
    CONCEPT_SCHEME_WITH_DSD_MEASURE_DIMENSION_ENUMERATED_REPRESENTATION,
    CODELIST_WITH_DSD_DIMENSION_ENUMERATED_REPRESENTATION,
    CONCEPT_SCHEMES_WITH_DSD_ROLES,
    CONCEPTS_WITH_DSD_ROLES,
    CONCEPT_SCHEMES_WITH_DSD_ATTRIBUTE,
    CONCEPT_WITH_DSD_ATTRIBUTE,
    CODELIST_WITH_DSD_ATTRIBUTE_ENUMERATED_REPRESENTATION,
    CODELIST_WITH_CONCEPT_ENUMERATED_REPRESENTATION,
    VARIABLE_ELEMENT_WITH_CODE,
    CODELIST_ORDER_FOR_DSD_DIMENSION,
    CODELIST_OPENNESS_LEVEL_FOR_DSD_DIMENSION,
    CODELIST_WITH_QUANTITY_UNIT,
    CODE_WITH_QUANTITY_UNIT,
    CONCEPT_SCHEME_WITH_QUANTITY_NUMERATOR,
    CONCEPT_WITH_QUANTITY_NUMERATOR,
    CONCEPT_SCHEME_WITH_QUANTITY_DENOMINATOR,
    CONCEPT_WITH_QUANTITY_DENOMINATOR,
    CONCEPT_SCHEME_WITH_QUANTITY_BASE_QUANTITY,
    CONCEPT_WITH_QUANTITY_BASE_QUANTITY,
    CONCEPT_SCHEME_WITH_CONCEPT_ENUMERATED_REPRESENTATION,
    CODELIST_THAT_CAN_BE_REPLACED,
    CATEGORY_SCHEMES_FOR_CATEGORISATIONS,
    CATEGORIES_FOR_CATEGORISATIONS,
    CODELIST_WITH_VARIABLE_ELEMENT_GEOGRAPHICAL_GRANULARITY,
    CODES_WITH_VARIABLE_ELEMENT_GEOGRAPHICAL_GRANULARITY;

    private StructuralResourcesRelationEnum() {
    }

    public String getName() {
        return name();
    }
}
