CREATE sequence SEQ_M_CONCEPT_SCHEMES_VERSIONS;
CREATE sequence SEQ_M_CONCEPTS;
CREATE sequence SEQ_M_CONCEPT_TYPES;
CREATE sequence SEQ_M_DATASTRUCTURE_VERSIONS;
CREATE sequence SEQ_M_ORG_SCHEMES_VERSIONS;
CREATE sequence SEQ_M_ORGANISATIONS;
CREATE sequence SEQ_M_CAT_SCHEMES_VERSIONS;
CREATE sequence SEQ_M_CATEGORIES;