-- Create normal entities
    
CREATE TABLE TB_M_CONCEPT_SCHEMES_VERSIONS (
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR2(50),
  PRODUCTION_VALIDATION_DATE TIMESTAMP,
  PRODUCTION_VALIDATION_USER VARCHAR2(255),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR2(50),
  DIFFUSION_VALIDATION_DATE TIMESTAMP,
  DIFFUSION_VALIDATION_USER VARCHAR2(255),
  INTERNAL_PUBLICATION_DATE_TZ VARCHAR2(50),
  INTERNAL_PUBLICATION_DATE TIMESTAMP,
  INTERNAL_PUBLICATION_USER VARCHAR2(255),
  EXTERNAL_PUBLICATION_DATE_TZ VARCHAR2(50),
  EXTERNAL_PUBLICATION_DATE TIMESTAMP,
  EXTERNAL_PUBLICATION_USER VARCHAR2(255),
  IS_EXTERNAL_PUBLICATION_I27 NUMBER(1,0),
  IS_EXTERNAL_PUBLICATION_F41 NUMBER(1,0),
  EXTERNAL_PUBLICATION_FAIL39_TZ VARCHAR2(50),
  EXTERNAL_PUBLICATION_FAIL39 TIMESTAMP,
  UPDATE_DATE_METAMAC_TZ VARCHAR2(50),
  UPDATE_DATE_METAMAC TIMESTAMP,
  RELATED_OPERATION_FK NUMBER(19),
  PROC_STATUS VARCHAR2(40) NOT NULL,
  CONCEPT_SCHEME_TYPE VARCHAR2(40) NOT NULL,
  TB_CONCEPT_SCHEMES_VERSIONS NUMBER(19) NOT NULL

);



-- Create many to many relations
    

-- Primary keys
    
    

-- Unique constraints
    



-- Foreign key constraints
ALTER TABLE TB_M_CONCEPT_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_M_CONCEPT_SCHEMES_VERS79
	FOREIGN KEY (TB_CONCEPT_SCHEMES_VERSIONS) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;


ALTER TABLE TB_M_CONCEPT_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_M_CONCEPT_SCHEMES_VERS66
	FOREIGN KEY (RELATED_OPERATION_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;

  

    

-- Index


    