-- ###########################################
-- # Create
-- ###########################################
-- Create pk sequence
    


-- Create normal entities
    
CREATE TABLE TB_ANNOTABLE_ARTEFACTS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  ANNOTABLE_ARTEFACT_TYPE VARCHAR2(31) NOT NULL,
  ID_LOGIC VARCHAR2(255),
  URI VARCHAR2(255),
  URN VARCHAR2(255),
  REPLACED_BY VARCHAR2(255),
  REPLACE_TO VARCHAR2(255),
  CONCEPT_IDENTITY_FK NUMBER(19),
  REPRESENTATION_FK NUMBER(19),
  COMPONENTLIST_FK NUMBER(19),
  NAME_FK NUMBER(19),
  DESCRIPTION_FK NUMBER(19),
  RELATE_TO NUMBER(19),
  USAGE_STATUS VARCHAR2(40),
  ORDER_LOGIC NUMBER(10),
  IS_ATTACHMENT_CONSTRAINT NUMBER(1,0),
  VERSION_LOGIC VARCHAR2(255),
  VALID_FROM_TZ VARCHAR2(50),
  VALID_FROM TIMESTAMP,
  VALID_TO_TZ VARCHAR2(50),
  VALID_TO TIMESTAMP,
  FINAL_LOGIC NUMBER(1,0),
  IS_EXTERNAL_REFERENCE NUMBER(1,0),
  STRUCTURE_URL VARCHAR2(255),
  SERVICE_URL VARCHAR2(255),
  IS_LAST_VERSION NUMBER(1,0),
  MAINTAINER_FK NUMBER(19),
  PROC_STATUS VARCHAR2(40),
  STRUCTURE_FK NUMBER(19)
);


CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID NUMBER(19) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TB_ITEM_SCHEMES (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TB_EXTERNAL_ITEMS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(255) NOT NULL,
  URI VARCHAR2(4000) NOT NULL,
  URN VARCHAR2(4000) NOT NULL,
  MANAGEMENT_APP_URL VARCHAR2(255),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19),
  TYPE VARCHAR2(40) NOT NULL
);


CREATE TABLE TB_ITEM_SCHEMES_VERSIONS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  ITEM_SCHEME_FK NUMBER(19) NOT NULL,
  MAINTANABLE_ARTIFACT_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_ITEMS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  NAMEABLE_ARTIFACT_FK NUMBER(19) NOT NULL,
  ITEM_SCHEME_VERSION_FK NUMBER(19),
  PARENT_FK NUMBER(19)
);


CREATE TABLE TB_REPRESENTATIONS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DTYPE VARCHAR2(31) NOT NULL,
  ENUMERATED_FK NUMBER(19),
  FACET_FK NUMBER(19)
);


CREATE TABLE TB_CONCEPTS (
  ISO_CONCEPT_REFERENCE_AGE46 VARCHAR2(255),
  ISO_CONCEPT_REFERENCE_SCH36 VARCHAR2(255),
  ISO_CONCEPT_REFERENCE_ID VARCHAR2(255),
  CORE_REPRESENTATION NUMBER(19),
  TB_ITEMS NUMBER(19) NOT NULL

);


CREATE TABLE TB_CONCEPT_SCHEMES_VERSIONS (
  TB_ITEM_SCHEMES_VERSIONS NUMBER(19) NOT NULL

);


CREATE TABLE TB_ANNOTATIONS (
  ID NUMBER(19) NOT NULL,
  ID_LOGIC VARCHAR2(255),
  TITLE VARCHAR2(255),
  TYPE VARCHAR2(255),
  URL VARCHAR2(255),
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONALSTRING_FK NUMBER(19),
  ANNOTATION_FK NUMBER(19)
);


CREATE TABLE TB_FACETS (
  ID NUMBER(19) NOT NULL,
  IS_SEQUENCE_FT VARCHAR2(255),
  INTERVAL_FT VARCHAR2(255),
  START_VALUE_FT VARCHAR2(255),
  END_VALUE_FT VARCHAR2(255),
  TIME_INTERVAL_FT VARCHAR2(14),
  START_TIME_FT VARCHAR2(255),
  END_TIME_FT VARCHAR2(255),
  MIN_LENGTH_FT VARCHAR2(255),
  MAX_LENGTH_FT VARCHAR2(255),
  MIN_VALUE_FT VARCHAR2(255),
  MAX_VALUE_FT VARCHAR2(255),
  DECIMALS_FT VARCHAR2(255),
  PATTERN_FT VARCHAR2(255),
  XHTML_EFT VARCHAR2(255),
  IS_MULTI_LINGUAL VARCHAR2(255),
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  FACET_VALUE VARCHAR2(255) NOT NULL
);


CREATE TABLE TB_LOCALISED_STRINGS (
  ID NUMBER(19) NOT NULL,
  LABEL VARCHAR2(4000) NOT NULL,
  LOCALE VARCHAR2(255) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONAL_STRING_FK NUMBER(19)
);


CREATE TABLE TB_ATTR_RELATIONSHIPS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DTYPE VARCHAR2(31) NOT NULL,
  GROUP_KEY NUMBER(19)
);



-- Create many to many relations
    
CREATE TABLE TB_COMPLIST_COMP (
  COMPONENT_FK NUMBER(19) NOT NULL,
  COMPONENTLIST_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_DATA_ATTRIBUTES_EI_ROLES (
  ROLE_FK NUMBER(19) NOT NULL,
  TB_DATA_ATTRIBUTES NUMBER(19) NOT NULL
);


CREATE TABLE TB_DIMENSIONS_EI_ROLES (
  ROLE_FK NUMBER(19) NOT NULL,
  TB_DIMENSIONS NUMBER(19) NOT NULL
);


CREATE TABLE TB_DIMREL_DIMCOM (
  DIMENSION_COMPONENT_FK NUMBER(19) NOT NULL,
  DIMENSION_RELATIONSHIP_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_DIMREL_GROUPDIM (
  GROUPDIMENSION_DESCRIPTOR_FK NUMBER(19) NOT NULL,
  DIMENSION_RELATIONSHIP_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_MEASURE_DIMEN_EI_ROLES (
  ROLE_FK NUMBER(19) NOT NULL,
  TB_MEASURE_DIMENSIONS NUMBER(19) NOT NULL
);



-- Primary keys
    
ALTER TABLE TB_ANNOTABLE_ARTEFACTS ADD CONSTRAINT PK_TB_ANNOTABLE_ARTEFACTS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ITEM_SCHEMES ADD CONSTRAINT PK_TB_ITEM_SCHEMES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ITEM_SCHEMES_VERSIONS ADD CONSTRAINT PK_TB_ITEM_SCHEMES_VERSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ITEMS ADD CONSTRAINT PK_TB_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_REPRESENTATIONS ADD CONSTRAINT PK_TB_REPRESENTATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ANNOTATIONS ADD CONSTRAINT PK_TB_ANNOTATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_FACETS ADD CONSTRAINT PK_TB_FACETS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ATTR_RELATIONSHIPS ADD CONSTRAINT PK_TB_ATTR_RELATIONSHIPS
	PRIMARY KEY (ID)
;

    
ALTER TABLE TB_COMPLIST_COMP ADD CONSTRAINT PK_TB_COMPLIST_COMP
	PRIMARY KEY (COMPONENT_FK, COMPONENTLIST_FK)
;

ALTER TABLE TB_DATA_ATTRIBUTES_EI_ROLES ADD CONSTRAINT PK_TB_DATA_ATTRIBUTES_EI_ROLES
	PRIMARY KEY (ROLE_FK, TB_DATA_ATTRIBUTES)
;

ALTER TABLE TB_DIMENSIONS_EI_ROLES ADD CONSTRAINT PK_TB_DIMENSIONS_EI_ROLES
	PRIMARY KEY (ROLE_FK, TB_DIMENSIONS)
;

ALTER TABLE TB_DIMREL_DIMCOM ADD CONSTRAINT PK_TB_DIMREL_DIMCOM
	PRIMARY KEY (DIMENSION_COMPONENT_FK, DIMENSION_RELATIONSHIP_FK)
;

ALTER TABLE TB_DIMREL_GROUPDIM ADD CONSTRAINT PK_TB_DIMREL_GROUPDIM
	PRIMARY KEY (GROUPDIMENSION_DESCRIPTOR_FK, DIMENSION_RELATIONSHIP_FK)
;

ALTER TABLE TB_MEASURE_DIMEN_EI_ROLES ADD CONSTRAINT PK_TB_MEASURE_DIMEN_EI_ROLES
	PRIMARY KEY (ROLE_FK, TB_MEASURE_DIMENSIONS)
;


-- Unique constraints
    

ALTER TABLE TB_ANNOTABLE_ARTEFACTS
    ADD CONSTRAINT UQ_TB_ANNOTABLE_ARTEFACTS UNIQUE (UUID)
;




ALTER TABLE TB_ITEM_SCHEMES
    ADD CONSTRAINT UQ_TB_ITEM_SCHEMES UNIQUE (UUID)
;




ALTER TABLE TB_ITEM_SCHEMES_VERSIONS
    ADD CONSTRAINT UQ_TB_ITEM_SCHEMES_VERSIONS UNIQUE (UUID)
;



ALTER TABLE TB_ITEMS
    ADD CONSTRAINT UQ_TB_ITEMS UNIQUE (UUID)
;



ALTER TABLE TB_REPRESENTATIONS
    ADD CONSTRAINT UQ_TB_REPRESENTATIONS UNIQUE (UUID)
;







ALTER TABLE TB_ANNOTATIONS
    ADD CONSTRAINT UQ_TB_ANNOTATIONS UNIQUE (UUID)
;



ALTER TABLE TB_FACETS
    ADD CONSTRAINT UQ_TB_FACETS UNIQUE (UUID)
;




ALTER TABLE TB_ATTR_RELATIONSHIPS
    ADD CONSTRAINT UQ_TB_ATTR_RELATIONSHIPS UNIQUE (UUID)
;



-- Foreign key constraints
ALTER TABLE TB_CONCEPTS ADD CONSTRAINT FK_TB_CONCEPTS_TB_ITEMS
	FOREIGN KEY (TB_ITEMS) REFERENCES TB_ITEMS (ID)
;
ALTER TABLE TB_CONCEPT_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_CONCEPT_SCHEMES_VERSIO46
	FOREIGN KEY (TB_ITEM_SCHEMES_VERSIONS) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID)
;


  
ALTER TABLE TB_ANNOTATIONS ADD CONSTRAINT FK_TB_ANNOTATIONS_TB_ANNOTAB37
	FOREIGN KEY (ANNOTATION_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_TB_I97
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_ITEM_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_ITEM_SCHEMES_VERSIONS_51
	FOREIGN KEY (ITEM_SCHEME_FK) REFERENCES TB_ITEM_SCHEMES (ID) ON DELETE CASCADE
;
ALTER TABLE TB_ITEM_SCHEMES_VERSIONS ADD CONSTRAINT FK_TB_ITEM_SCHEMES_VERSIONS_23
	FOREIGN KEY (MAINTANABLE_ARTIFACT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_ITEMS ADD CONSTRAINT FK_TB_ITEMS_NAMEABLE_ARTIFAC52
	FOREIGN KEY (NAMEABLE_ARTIFACT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_ITEMS ADD CONSTRAINT FK_TB_ITEMS_ITEM_SCHEME_VERS50
	FOREIGN KEY (ITEM_SCHEME_VERSION_FK) REFERENCES TB_ITEM_SCHEMES_VERSIONS (ID) ON DELETE CASCADE
;

ALTER TABLE TB_ITEMS ADD CONSTRAINT FK_TB_ITEMS_TB_ITEMS
	FOREIGN KEY (PARENT_FK) REFERENCES TB_ITEMS (ID)
;

  
  
ALTER TABLE TB_CONCEPTS ADD CONSTRAINT FK_TB_CONCEPTS_CORE_REPRESEN26
	FOREIGN KEY (CORE_REPRESENTATION) REFERENCES TB_REPRESENTATIONS (ID)
;

  
  
  
ALTER TABLE TB_ANNOTATIONS ADD CONSTRAINT FK_TB_ANNOTATIONS_INTERNATIO31
	FOREIGN KEY (INTERNATIONALSTRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
  
  
  
  
  
  

ALTER TABLE TB_COMPLIST_COMP ADD CONSTRAINT FK_TB_COMPLIST_COMP_COMPONEN86
	FOREIGN KEY (COMPONENT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_COMPLIST_COMP ADD CONSTRAINT FK_TB_COMPLIST_COMP_COMPONEN52
	FOREIGN KEY (COMPONENTLIST_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_DATA_ATTRIBUTES_EI_ROLES ADD CONSTRAINT FK_TB_DATA_ATTRIBUTES_EI_ROL77
	FOREIGN KEY (ROLE_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_DATA_ATTRIBUTES_EI_ROLES ADD CONSTRAINT FK_TB_DATA_ATTRIBUTES_EI_ROL36
	FOREIGN KEY (TB_DATA_ATTRIBUTES) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_DIMENSIONS_EI_ROLES ADD CONSTRAINT FK_TB_DIMENSIONS_EI_ROLES_RO10
	FOREIGN KEY (ROLE_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_DIMENSIONS_EI_ROLES ADD CONSTRAINT FK_TB_DIMENSIONS_EI_ROLES_TB06
	FOREIGN KEY (TB_DIMENSIONS) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  
ALTER TABLE TB_DIMREL_DIMCOM ADD CONSTRAINT FK_TB_DIMREL_DIMCOM_DIMENSIO37
	FOREIGN KEY (DIMENSION_COMPONENT_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_DIMREL_DIMCOM ADD CONSTRAINT FK_TB_DIMREL_DIMCOM_DIMENSIO18
	FOREIGN KEY (DIMENSION_RELATIONSHIP_FK) REFERENCES TB_ATTR_RELATIONSHIPS (ID)
;

  
ALTER TABLE TB_DIMREL_GROUPDIM ADD CONSTRAINT FK_TB_DIMREL_GROUPDIM_GROUPD34
	FOREIGN KEY (GROUPDIMENSION_DESCRIPTOR_FK) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;
ALTER TABLE TB_DIMREL_GROUPDIM ADD CONSTRAINT FK_TB_DIMREL_GROUPDIM_DIMENS06
	FOREIGN KEY (DIMENSION_RELATIONSHIP_FK) REFERENCES TB_ATTR_RELATIONSHIPS (ID)
;

  
ALTER TABLE TB_MEASURE_DIMEN_EI_ROLES ADD CONSTRAINT FK_TB_MEASURE_DIMEN_EI_ROLES05
	FOREIGN KEY (ROLE_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_MEASURE_DIMEN_EI_ROLES ADD CONSTRAINT FK_TB_MEASURE_DIMEN_EI_ROLES30
	FOREIGN KEY (TB_MEASURE_DIMENSIONS) REFERENCES TB_ANNOTABLE_ARTEFACTS (ID)
;

  


-- Index
CREATE INDEX IX_TB_ANNOTABLE_ARTEFACTS_AN46
    ON TB_ANNOTABLE_ARTEFACTS (ANNOTABLE_ARTEFACT_TYPE ASC)
;
CREATE INDEX IX_TB_REPRESENTATIONS_DTYPE
    ON TB_REPRESENTATIONS (DTYPE ASC)
;
CREATE INDEX IX_TB_ATTR_RELATIONSHIPS_DTYPE
    ON TB_ATTR_RELATIONSHIPS (DTYPE ASC)
;


