package org.siemac.metamac.srm.core.code.serviceapi.utils;

import org.siemac.metamac.srm.core.base.utils.BaseDoMocks;
import org.siemac.metamac.srm.core.code.domain.CodeMetamac;
import org.siemac.metamac.srm.core.code.domain.CodelistVersionMetamac;
import org.siemac.metamac.srm.core.code.enume.domain.AccessTypeEnum;
import org.siemac.metamac.srm.core.organisation.domain.OrganisationMetamac;

import com.arte.statistic.sdmx.srm.core.code.serviceapi.utils.CodesDoMocks;

public class CodesMetamacDoMocks extends CodesDoMocks {

    public static CodelistVersionMetamac mockCodelist(OrganisationMetamac maintainer) {
        CodelistVersionMetamac codelistVersion = new CodelistVersionMetamac();

        codelistVersion.setShortName(mockInternationalString());
        codelistVersion.setIsRecommended(Boolean.FALSE);
        codelistVersion.setAccessType(AccessTypeEnum.RESTRICTED);

        mockCodelist(codelistVersion, maintainer);
        return codelistVersion;
    }

    public static void fillCodelistAutogeneratedMetadata(CodelistVersionMetamac entity) {
        entity.setLifeCycleMetadata(BaseDoMocks.mockLifeCycle());
        CodesDoMocks.fillCodelistAutogeneratedMetadata(entity);
    }

    public static CodeMetamac mockCode() {
        CodeMetamac codeMetamac = new CodeMetamac();
        mockCode(codeMetamac);
        return codeMetamac;
    }

    public static void fillCodeAutogeneratedMetadata(CodeMetamac entity) {
        CodesDoMocks.fillCodeAutogeneratedMetadata(entity);
    }

}
