package org.siemac.metamac.srm.core.organisation.serviceapi.utils;

import org.siemac.metamac.core.common.ent.domain.ExternalItem;
import org.siemac.metamac.core.common.enume.domain.TypeExternalArtefactsEnum;
import org.siemac.metamac.srm.core.base.utils.BaseDoMocks;
import org.siemac.metamac.srm.core.organisation.domain.OrganisationMetamac;
import org.siemac.metamac.srm.core.organisation.domain.OrganisationSchemeVersionMetamac;

import com.arte.statistic.sdmx.srm.core.organisation.serviceapi.utils.OrganisationsDoMocks;
import com.arte.statistic.sdmx.v2_1.domain.enume.organisation.domain.OrganisationSchemeTypeEnum;
import com.arte.statistic.sdmx.v2_1.domain.enume.organisation.domain.OrganisationTypeEnum;

public class OrganisationsMetamacDoMocks extends OrganisationsDoMocks {

    public static OrganisationSchemeVersionMetamac mockOrganisationScheme(OrganisationSchemeTypeEnum organisationSchemeType, OrganisationMetamac maintainer) {
        OrganisationSchemeVersionMetamac organisationSchemeVersion = new OrganisationSchemeVersionMetamac();
        organisationSchemeVersion.setOrganisationSchemeType(organisationSchemeType);
        mockOrganisationScheme(organisationSchemeVersion, maintainer);
        return organisationSchemeVersion;
    }

    public static void fillOrganisationSchemeAutogeneratedMetadata(OrganisationSchemeVersionMetamac entity) {
        entity.setLifeCycleMetadata(BaseDoMocks.mockLifeCycle());
        OrganisationsDoMocks.fillOrganisationSchemeAutogeneratedMetadata(entity);
    }

    public static OrganisationMetamac mockOrganisation(OrganisationTypeEnum organisationType) {
        OrganisationMetamac organisation = new OrganisationMetamac();
        organisation.setOrganisationType(organisationType);
        mockOrganisation(organisation);
        return organisation;
    }

    public static void fillOrganisationAutogeneratedMetadata(OrganisationMetamac entity) {
        OrganisationsDoMocks.fillOrganisationAutogeneratedMetadata(entity);
    }

    public static ExternalItem mockOperationExternalItem(String code) {
        return new ExternalItem(code, "http://" + code, "urn:" + code, TypeExternalArtefactsEnum.STATISTICAL_OPERATION);
    }
}