
    
-- ###########################################
-- # Drop
-- ###########################################


-- Disable Foreign key constraints
ALTER TABLE TB_ORGANISATIONS DROP CONSTRAINT FK_TB_ORGANISATIONS_TB_ITEMS;
ALTER TABLE TB_CONCEPTS DROP CONSTRAINT FK_TB_CONCEPTS_TB_ITEMS;
ALTER TABLE TB_CONCEPT_SCHEMES_VERSIONS DROP CONSTRAINT FK_TB_CONCEPT_SCHEMES_VERSIONS_TB_ITEM_SCHEMES_VERSIONS;
ALTER TABLE TB_CODELISTS_VERSIONS DROP CONSTRAINT FK_TB_CODELISTS_VERSIONS_TB_ITEM_SCHEMES_VERSIONS;
ALTER TABLE TB_CATEGORIES DROP CONSTRAINT FK_TB_CATEGORIES_TB_ITEMS;
ALTER TABLE TB_CAT_SCHEMES_VERSIONS DROP CONSTRAINT FK_TB_CAT_SCHEMES_VERSIONS_TB_ITEM_SCHEMES_VERSIONS;
ALTER TABLE TB_CODES DROP CONSTRAINT FK_TB_CODES_TB_ITEMS;
ALTER TABLE TB_ORG_SCHEMES_VERSIONS DROP CONSTRAINT FK_TB_ORG_SCHEMES_VERSIONS_TB_ITEM_SCHEMES_VERSIONS;
ALTER TABLE TB_DATASTRUCTURE_VERSIONS DROP CONSTRAINT FK_TB_DATASTRUCTURE_VERSIONS_TB_STRUCTURES_VERSIONS;


  
  
ALTER TABLE TB_EXTERNAL_ITEMS DROP CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK;

  
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK;

  
  
ALTER TABLE TB_ANNOTATIONS DROP CONSTRAINT FK_TB_ANNOTATIONS_TB_ANNOTABLE_ARTEFACTS;

ALTER TABLE TB_ANNOTATIONS DROP CONSTRAINT FK_TB_ANNOTATIONS_TEXT_FK;

  
  
  
  
  
ALTER TABLE TB_ITEM_SCHEMES_VERSIONS DROP CONSTRAINT FK_TB_ITEM_SCHEMES_VERSIONS_ITEM_SCHEME_FK;
ALTER TABLE TB_ITEM_SCHEMES_VERSIONS DROP CONSTRAINT FK_TB_ITEM_SCHEMES_VERSIONS_MAINTANABLE_ARTEFACT_FK;

  
ALTER TABLE TB_ITEMS DROP CONSTRAINT FK_TB_ITEMS_NAMEABLE_ARTEFACT_FK;
ALTER TABLE TB_ITEMS DROP CONSTRAINT FK_TB_ITEMS_PARENT_FK;
ALTER TABLE TB_ITEMS DROP CONSTRAINT FK_TB_ITEMS_ITEM_SCHEME_VERSION_FK;
ALTER TABLE TB_ITEMS DROP CONSTRAINT FK_TB_ITEMS_ITEM_SCHEME_VERSION_FIRST_FK;

  
  
  
ALTER TABLE TB_CONCEPTS DROP CONSTRAINT FK_TB_CONCEPTS_CORE_REPRESENTATION_FK;

  
  
  
  
  
  
  
  
  
ALTER TABLE TB_STRUCTURES_VERSIONS DROP CONSTRAINT FK_TB_STRUCTURES_VERSIONS_MAINTANABLE_ARTEFACT_FK;
ALTER TABLE TB_STRUCTURES_VERSIONS DROP CONSTRAINT FK_TB_STRUCTURES_VERSIONS_STRUCTURE_FK;

  
  
  
ALTER TABLE TB_CATEGORISATIONS DROP CONSTRAINT FK_TB_CATEGORISATIONS_MAINTANABLE_ARTEFACT_FK;
ALTER TABLE TB_CATEGORISATIONS DROP CONSTRAINT FK_TB_CATEGORISATIONS_CATEGORY_FK;
ALTER TABLE TB_CATEGORISATIONS DROP CONSTRAINT FK_TB_CATEGORISATIONS_ARTEFACT_CATEGORISED_FK;

  
  
  
  
  
  
  
ALTER TABLE TB_EXCEPTION_IMPORT DROP CONSTRAINT FK_TB_EXCEPTION_IMPORT_IMPORT_DATA_FK;

  
ALTER TABLE TB_CONTACTS DROP CONSTRAINT FK_TB_CONTACTS_NAME_FK;
ALTER TABLE TB_CONTACTS DROP CONSTRAINT FK_TB_CONTACTS_ORGANISATION_UNIT_FK;
ALTER TABLE TB_CONTACTS DROP CONSTRAINT FK_TB_CONTACTS_RESPONSIBILITY_FK;
ALTER TABLE TB_CONTACTS DROP CONSTRAINT FK_TB_CONTACTS_ORGANISATION_FK;

  
ALTER TABLE TB_CONTACT_ITEMS DROP CONSTRAINT FK_TB_CONTACT_ITEMS_CONTACT_FK;

  
  
  
  
  
  
  

ALTER TABLE TB_COMPLIST_COMP DROP CONSTRAINT FK_TB_COMPLIST_COMP_COMPONENT_FK;
ALTER TABLE TB_COMPLIST_COMP DROP CONSTRAINT FK_TB_COMPLIST_COMP_COMPONENTLIST_FK;

  
ALTER TABLE TB_DATA_ATTRIBUTES_EI_ROLES DROP CONSTRAINT FK_TB_DATA_ATTRIBUTES_EI_ROLES_ROLE_FK;
ALTER TABLE TB_DATA_ATTRIBUTES_EI_ROLES DROP CONSTRAINT FK_TB_DATA_ATTRIBUTES_EI_ROLES_TB_DATA_ATTRIBUTES;

  
ALTER TABLE TB_DIMENSIONS_EI_ROLES DROP CONSTRAINT FK_TB_DIMENSIONS_EI_ROLES_ROLE_FK;
ALTER TABLE TB_DIMENSIONS_EI_ROLES DROP CONSTRAINT FK_TB_DIMENSIONS_EI_ROLES_TB_DIMENSIONS;

  
ALTER TABLE TB_DIMREL_DIMCOM DROP CONSTRAINT FK_TB_DIMREL_DIMCOM_DIMENSION_COMPONENT_FK;
ALTER TABLE TB_DIMREL_DIMCOM DROP CONSTRAINT FK_TB_DIMREL_DIMCOM_DIMENSION_RELATIONSHIP_FK;

  
ALTER TABLE TB_DIMREL_GROUPDIM DROP CONSTRAINT FK_TB_DIMREL_GROUPDIM_GROUPDIMENSION_DESCRIPTOR_FK;
ALTER TABLE TB_DIMREL_GROUPDIM DROP CONSTRAINT FK_TB_DIMREL_GROUPDIM_DIMENSION_RELATIONSHIP_FK;

  
ALTER TABLE TB_MEASURE_DIMEN_EI_ROLES DROP CONSTRAINT FK_TB_MEASURE_DIMEN_EI_ROLES_ROLE_FK;
ALTER TABLE TB_MEASURE_DIMEN_EI_ROLES DROP CONSTRAINT FK_TB_MEASURE_DIMEN_EI_ROLES_TB_MEASURE_DIMENSIONS;

  
ALTER TABLE TB_STRVERSION_COMPLIST DROP CONSTRAINT FK_TB_STRVERSION_COMPLIST_STRUCTUREVERSION_FK;
ALTER TABLE TB_STRVERSION_COMPLIST DROP CONSTRAINT FK_TB_STRVERSION_COMPLIST_COMPONENT_LIST_FK;

  

    
-- Drop many to many relations
    
DROP TABLE TB_STRVERSION_COMPLIST;

DROP TABLE TB_MEASURE_DIMEN_EI_ROLES;

DROP TABLE TB_DIMREL_GROUPDIM;

DROP TABLE TB_DIMREL_DIMCOM;

DROP TABLE TB_DIMENSIONS_EI_ROLES;

DROP TABLE TB_DATA_ATTRIBUTES_EI_ROLES;

DROP TABLE TB_COMPLIST_COMP;

-- Drop normal entities
    
DROP TABLE TB_DATASTRUCTURE_VERSIONS;

DROP TABLE TB_ATTR_RELATIONSHIPS;

DROP TABLE TB_ORG_SCHEMES_VERSIONS;

DROP TABLE TB_CONTACT_ITEMS;

DROP TABLE TB_CONTACTS;

DROP TABLE TB_EXCEPTION_IMPORT;

DROP TABLE TB_IMPORT_DATAS;

DROP TABLE TB_CODES;

DROP TABLE TB_CAT_SCHEMES_VERSIONS;

DROP TABLE TB_CATEGORISATIONS;

DROP TABLE TB_CATEGORIES;

DROP TABLE TB_STRUCTURES_VERSIONS;

DROP TABLE TB_STRUCTURES;

DROP TABLE TB_FACETS;

DROP TABLE TB_CODELISTS_VERSIONS;

DROP TABLE TB_CONCEPT_SCHEMES_VERSIONS;

DROP TABLE TB_CONCEPTS;

DROP TABLE TB_REPRESENTATIONS;

DROP TABLE TB_ITEMS;

DROP TABLE TB_ITEM_SCHEMES_VERSIONS;

DROP TABLE TB_ORGANISATIONS;

DROP TABLE TB_ITEM_SCHEMES;

DROP TABLE TB_ANNOTATIONS;

DROP TABLE TB_ANNOTABLE_ARTEFACTS;

DROP TABLE TB_LOCALISED_STRINGS;

DROP TABLE TB_EXTERNAL_ITEMS;

DROP TABLE TB_INTERNATIONAL_STRINGS;