-- Items
CREATE INDEX IX_TB_M_CODES_FK ON TB_M_CODES (TB_CODES);

CREATE INDEX IX_TB_M_CONCEPTS_FK ON TB_M_CONCEPTS (TB_CONCEPTS);
CREATE INDEX IX_TB_M_CONCEPTS_EXTENDS_FK ON TB_M_CONCEPTS (EXTENDS_FK);
CREATE INDEX IX_TB_CONCEPT_ROLES_ROLE_FK ON TB_M_CONCEPT_ROLES (CONCEPT_ROLE_FK);
CREATE INDEX IX_TB_CONCEPT_ROLES_CONCEPT_FK ON TB_M_CONCEPT_ROLES (CONCEPT_FK);

CREATE INDEX IX_TB_M_ORGANISATIONS_FK ON TB_M_ORGANISATIONS (TB_ORGANISATIONS);

CREATE INDEX IX_TB_M_CATEGORIES_FK ON TB_M_CATEGORIES (TB_CATEGORIES);

-- Item schemes
CREATE INDEX IX_TB_M_CODELISTS_V_FK ON TB_M_CODELISTS_VERSIONS (TB_CODELISTS_VERSIONS);
CREATE INDEX IX_TB_M_CONCEPTS_SCHEMES_V_FK ON TB_M_CONCEPT_SCHEMES_VERSIONS (TB_CONCEPT_SCHEMES_VERSIONS);
CREATE INDEX IX_TB_M_ORG_SCHEMES_V_FK ON TB_M_ORG_SCHEMES_VERSIONS (TB_ORG_SCHEMES_VERSIONS);
CREATE INDEX IX_TB_M_CAT_SCHEMES_V_FK ON TB_M_CAT_SCHEMES_VERSIONS (TB_CAT_SCHEMES_VERSIONS);
CREATE INDEX IX_TB_M_DATASTRUCTURE_V_FK ON TB_M_DATASTRUCTURE_VERSIONS (TB_DATASTRUCTURE_VERSIONS);
