-- AGENCY SCHEME: SDMX

INSERT INTO TB_M_ORG_SCHEMES_VERSIONS
	(TB_ORG_SCHEMES_VERSIONS, PROC_STATUS, 
     PRODUCTION_VALIDATION_DATE_TZ, PRODUCTION_VALIDATION_DATE, PRODUCTION_VALIDATION_USER,
     DIFFUSION_VALIDATION_DATE_TZ, DIFFUSION_VALIDATION_DATE, DIFFUSION_VALIDATION_USER,
     INTERNAL_PUBLICATION_DATE_TZ, INTERNAL_PUBLICATION_DATE, INTERNAL_PUBLICATION_USER,
     EXTERNAL_PUBLICATION_DATE_TZ, EXTERNAL_PUBLICATION_DATE, EXTERNAL_PUBLICATION_USER)
VALUES
	(GET_NEXT_SEQUENCE_VALUE('ITEM_SCHEMES_VERSIONS') - 1, 'INTERNALLY_PUBLISHED', 
	'Europe/London', to_timestamp('01/01/2012 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'), 'Metamac',
	'Europe/London', to_timestamp('01/01/2012 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'), 'Metamac',
	'Europe/London', to_timestamp('01/01/2012 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'), 'Metamac',
	null, null, null
	);
	
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'M_ORG_SCHEMES_VERSIONS';

