-- AGENCY SCHEME: SDMX

INSERT INTO TB_M_ORG_SCHEMES_VERSIONS
	(TB_ORG_SCHEMES_VERSIONS, PROC_STATUS)
VALUES
	(GET_NEXT_SEQUENCE_VALUE('ITEM_SCHEMES_VERSIONS') - 1, 'DRAFT');
	
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'M_ORG_SCHEMES_VERSIONS';

