DROP VIEW TB_FAM_CONCEPTOS;
DROP VIEW TB_CONC_FAMCONC;
DROP VIEW TB_CONCEPTOS;
DROP VIEW TB_CODIFICACIONES;
DROP VIEW TB_CODIGOS;
DROP VIEW TB_ITEMS;
DROP VIEW TB_ORDENES;
DROP VIEW TB_ORDENES_CODIGOS;